export const ACTION_NAME = {
  'CREATE_NEW_PHOTO': 'CREATE_NEW_PHOTO',
  'CREATE_NEW_MEMBER': 'CREATE_NEW_MEMBER',
  'UPDATE_MEMBER': 'UPDATE_MEMBER',
  'DELETE_MEMBER': 'DELETE_MEMBER',
  'UPDATE_USER': 'UPDATE_USER',
  'DELETE_USER': 'DELETE_USER'
}